image: archlinux/base

variables:
  GOPATH: $CI_PROJECT_DIR/go

before_script:
  - pacman -Sy --noconfirm base-devel go
  - mkdir $CI_PROJECT_DIR/src
  - shopt -s extglob
  - mv !(src|go) $CI_PROJECT_DIR/src
  - cd $CI_PROJECT_DIR/src

stages:
  - cache-mod
  - test
  - build

cache:
  key: $CI_COMMIT_SHA
  paths:
    - $CI_PROJECT_DIR/go/pkg/mod

cache-mod:
  script:
    - go get ./...
  artifacts:
    paths:
      - $CI_PROJECT_DIR/go/pkg/mod

  only:
    - tags

build-goblog:
  stage: build
  script:
    - mkdir -p $CI_PROJECT_DIR/goblog
    - go build -ldflags "-s -w" -trimpath -o $CI_PROJECT_DIR/goblog/goblog
    - cp config.default.json $CI_PROJECT_DIR/goblog
    - wget https://gitlab.com/xiayesuifeng/goblog-web/builds/artifacts/master/download?job=build-web -O web.zip
    - unzip web.zip
    - mv build $CI_PROJECT_DIR/goblog/web

  only:
    - tags

  artifacts:
    paths:
      - $CI_PROJECT_DIR/goblog

build-plugins:
  stage: build
  trigger: xiayesuifeng/goblog-plugins

  only:
    - tags

test:
  cache: {}
  script:
    - go build

  except:
    - tags