image: archlinux/base

variables:
  GOPATH: $CI_PROJECT_DIR/go

before_script:
  - pacman -Sy --noconfirm base-devel go
  - mkdir $CI_PROJECT_DIR/src
  - shopt -s extglob
  - mv !(src|go) $CI_PROJECT_DIR/src
  - cd $CI_PROJECT_DIR/src

stages:
  - cache-mod
  - test
  - build

cache:
  key: $CI_COMMIT_SHA
  paths:
    - $CI_PROJECT_DIR/go/pkg/mod

cache-mod:
  script:
    - go get ./...
  artifacts:
    paths:
      - $CI_PROJECT_DIR/go/pkg/mod

build-goblog:
  stage: build
  script:
    - go build
    - mkdir -p $CI_PROJECT_DIR/build
    - cp goblog $CI_PROJECT_DIR/build

  only:
    - tags

  artifacts:
    paths:
      - $CI_PROJECT_DIR/build/goblog

build-plugins:
  stage: build
  trigger: xiayesuifeng/goblog-plugins

test:
  cache: {}
  script:
    - go build

  except:
    - tags