image: base/devel

before_script:
  - pacman -Sy --noconfirm go git

stages:
  - build
  - test

build-goblog:
  stage: build
  script:
    - go build
    - mkdir -p $CI_PROJECT_DIR/build
    - cp goblog $CI_PROJECT_DIR/build

  only:
      - tags

  artifacts:
    paths:
      - $CI_PROJECT_DIR/build/goblog

test:
  script:
    - go build